services:
  postgres:
    image: postgres:latest
    container_name: ifunnyer-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: ifunnyer-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 20032002l

